# Generated by Django 5.2a1 on 2025-02-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting',
            name='id',
        ),
        migrations.AddField(
            model_name='batting',
            name='pk',
            field=models.CompositePrimaryKey('playerid', 'yearid', 'stint', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batting',
            name='playerid',
            field=models.ForeignKey(blank=True, db_column='playerID', on_delete=django.db.models.deletion.CASCADE, to='baseball_dashboard.people'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='stint',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='yearid',
            field=models.BigIntegerField(blank=True, db_column='yearID'),
        ),
    ]
